### PR TITLE
Maven to Gradle Migration

### PR DESCRIPTION
**Pull request by eankeen**
this modernizes the build system from maven to gradle

not only is gradle cool, but it has more terse configuration and makes it a lot easier to modify the build pipeline with built-in diagnostics and o11y tooling

If merged this will also close #112

### CODE REVIEW

**Comment by eankeen** [comment]
travis still has to be fixed; adding the Justfile was a mistake

**Comment by nice6599** [comment]
okay but i learned how to use maven so i would rather stick with that.

**Comment by ifvictr** [comment]
@eankeen Yep, this line specifically: https://github.com/hackclub/HCCore/blob/24d2a40472d63885188603a8908170c2c6caf40a/.travis.yml#L7. Also, could you the Gradle setup to the SETUP.md?

**Comment by eankeen** [comment]
it's good to go! i merged the same changes @ifvictr made in #112

**Comment by eankeen** [comment]
@nice6599 the process to add dependencies is very similar as well as the build commands. maybe look into it for a bit? The ecosystem as a whole is moving to Gradle where applicable

**Pull request merged**
